---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
      imp: critical
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: lohithgummi/st:v2.0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qdrant
      imp: moderate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant
          resources:
            limits:
              cpu: "2"
              memory: "6Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: nfs-volume
              mountPath: /snapshot
          volumes:
          - name: nfs-volume
            nfs:
              server: nfs-server.example.com
              path: /snapshot
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
spec:
  rules:
  - host: streamlit.lohithgummi.com 
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: chatbot-service
            port:
              number: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: full-blast-scaler
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatbot-deployment
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moderate-scaler
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qdrant-deployment
  targetCPUUtilizationPercentage: 70
